### ISSUE TITLE
Label for relays and sensors differ

### ISSUE THREAD

**Issue by masterflai** [ylabonte/ioBroker.procon-ip#31]
Version 1.2.1

My current instance shows always the label of the following element. For example relais 7 named as  "Heat pump" within Procon-IP is also named "Heat Pump", but the text label shows the valua of the following relay 8. Same for sensors.

Can you reproduce this issue?

What is correct in this case?
![2022-04-15 23_17_54-javascript - Pi4b](https://user-images.githubusercontent.com/32191717/163634383-f37652d9-ac51-40ee-853d-6b449963f895.jpg)

**Comment by ylabonte** [comment]
This should be an unintended side-effect of a change in the api library (https://github.com/ylabonte/procon-ip#release-v131). The object categories (sensors, relays, etc.) started counting with 1 in the past. Since this library change they are counting from 0. I could resolve this by working around the change in this adapter, but this could affect people that installed the adapter after that change or found a workaround be their own.

The solution to this problem is to delete the procon-ip object tree in your ioBroker installation and restart the adapter. All objects will automatically be recreated on adapter  (re)start.

Can you confirm that this solution worked for you?

**Comment by masterflai** [comment]
Thanks for the fast reply Yannik. The issue was solved by removing the objects, instance and the adapter and their reinstallation. Important: If someone is running scripts in these objects they need also a rework to point to the correct objects.

**Comment by ylabonte** [comment]
Thanks for the advice! :)
